spring:
  datasource:
    url: jdbc:h2:mem:testb
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false


# Security Configuration
keycloak:
  server-url: null
  realm: null
  client-id: null
  client-secret: null